# UNICODE_COMMON = yes
# UNICODEMAP_ENABLE = yes
# LEADER_ENABLE = yes
NKRO_ENABLE = yes
ENCODER_ENABLE = yes

CONSOLE_ENABLE = yes
CONVERT_TO = liatris

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = yes
RGBLIGHT_LAYERS = yes